# Generated by Django 2.2 on 2019-04-07 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Название книги')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Цена')),
                ('issue_year', models.IntegerField(null=True, verbose_name='Год издания')),
                ('available', models.BooleanField(default=True, verbose_name='Доступно для заказа')),
                ('rate', models.FloatField(default=0, verbose_name='Рейтинг')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('authors', models.ManyToManyField(to='catalog.Author', verbose_name='Авторы')),
                ('seria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.Seria', verbose_name='Серия')),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
            },
        ),
    ]
