# Generated by Django 2.2 on 2019-04-07 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='authors',
        ),
        migrations.RemoveField(
            model_name='book',
            name='seria',
        ),
        migrations.AddField(
            model_name='book',
            name='pages',
            field=models.IntegerField(null=True, verbose_name='Количество страниц'),
        ),
    ]
