# Generated by Django 2.2 on 2019-04-07 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20190407_2222'),
        ('book', '0002_auto_20190407_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(to='catalog.Author', verbose_name='Авторы'),
        ),
    ]
