# Generated by Django 2.2 on 2019-04-07 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_auto_20190407_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Перплет'),
        ),
        migrations.AddField(
            model_name='book',
            name='forma',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Формат'),
        ),
    ]
