# Generated by Django 2.2 on 2019-04-07 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0008_auto_20190407_2256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='cover',
        ),
        migrations.AddField(
            model_name='book',
            name='cover',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Переплет'),
        ),
        migrations.RemoveField(
            model_name='book',
            name='forma',
        ),
        migrations.AddField(
            model_name='book',
            name='forma',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Формат'),
        ),
    ]
