# Generated by Django 2.2 on 2019-04-07 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0009_auto_20190407_2305'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='isbn',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='ISBN'),
        ),
    ]
