# Generated by Django 2.2 on 2019-04-08 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0011_auto_20190408_2041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='age_restrictions',
        ),
    ]
