# Generated by Django 2.2 on 2019-04-08 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0012_remove_book_age_restrictions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.DecimalField(decimal_places=1, max_digits=8, verbose_name='Вес(гр)'),
        ),
    ]
