# Generated by Django 2.2 on 2019-04-08 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0013_auto_20190408_2107'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='age_restrictions',
            field=models.CharField(default=0, max_length=200, verbose_name='Возрастные ограничения'),
        ),
    ]
