# Generated by Django 2.2 on 2019-04-08 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0014_book_age_restrictions'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='number_of_book',
            field=models.IntegerField(max_length=200, null=True, verbose_name='Количество книг в наличии'),
        ),
    ]
