# Generated by Django 2.2 on 2019-04-08 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0015_book_number_of_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='number_of_book',
            field=models.IntegerField(null=True, verbose_name='Количество книг в наличии'),
        ),
    ]
