# Generated by Django 2.2 on 2019-04-08 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0016_auto_20190408_2135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='age_restrictions',
        ),
        migrations.AddField(
            model_name='book',
            name='restrictons',
            field=models.IntegerField(null=True, verbose_name='Возраст'),
        ),
        migrations.AddField(
            model_name='book',
            name='weight',
            field=models.DecimalField(decimal_places=1, max_digits=8, null=True, verbose_name='Вес(гр)'),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(max_length=200, null=True, verbose_name='ISBN'),
        ),
        migrations.AlterField(
            model_name='book',
            name='number_of_book',
            field=models.IntegerField(max_length=200, null=True, verbose_name='Количество книг в наличии'),
        ),
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='book',
            name='rate',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], unique=True, verbose_name='Рейтинг'),
        ),
    ]
