# Generated by Django 2.2 on 2019-04-08 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0018_auto_20190408_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='restrictons',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18)], null=True, verbose_name='Возрастные ограничения'),
        ),
    ]
