# Generated by Django 2.2 on 2019-04-09 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0019_auto_20190408_2234'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover_books',
            field=models.ImageField(height_field=100, max_length=200, null=True, upload_to='image', verbose_name='Обложка', width_field=100),
        ),
        migrations.AlterField(
            model_name='book',
            name='number_of_book',
            field=models.IntegerField(null=True, verbose_name='Количество книг в наличии'),
        ),
    ]
