# Generated by Django 2.2 on 2019-04-09 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0020_auto_20190409_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover_books',
            field=models.ImageField(max_length=200, null=True, upload_to='image', verbose_name='Обложка'),
        ),
    ]
