# Generated by Django 2.2 on 2019-04-09 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0021_auto_20190409_2302'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': 'Книга', 'verbose_name_plural': 'Книги'},
        ),
    ]
