# Generated by Django 2.2 on 2019-04-10 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0023_auto_20190410_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='name',
            field=models.CharField(default=False, max_length=200, verbose_name='Название книги'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='seria',
            field=models.ManyToManyField(related_name='books', to='catalog.Seria', verbose_name='Серия'),
        ),
    ]
