# Generated by Django 2.2 on 2019-04-07 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20190407_2057'),
    ]

    operations = [
        migrations.CreateModel(
            name='Сover',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Переплет')),
            ],
        ),
    ]
