# Generated by Django 2.2 on 2019-04-07 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_сover'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='сover',
            options={'verbose_name': 'Жанр'},
        ),
    ]
