# Generated by Django 2.2 on 2019-04-07 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_format'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Format',
        ),
        migrations.DeleteModel(
            name='Сover',
        ),
        migrations.AlterField(
            model_name='author',
            name='first_name',
            field=models.CharField(max_length=200, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='author',
            name='last_name',
            field=models.CharField(max_length=200, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название жанра'),
        ),
        migrations.AlterField(
            model_name='publishinghouse',
            name='description',
            field=models.TextField(max_length=200, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='publishinghouse',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название издательства'),
        ),
        migrations.AlterField(
            model_name='seria',
            name='description',
            field=models.TextField(max_length=200, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='seria',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Серия'),
        ),
    ]
