# Generated by Django 2.2 on 2019-04-07 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0009_auto_20190407_2305'),
        ('catalog', '0007_cover_format'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cover',
        ),
        migrations.DeleteModel(
            name='Format',
        ),
    ]
