# Generated by Django 2.2 on 2019-04-08 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_agerestrictions'),
    ]

    operations = [
        migrations.AddField(
            model_name='agerestrictions',
            name='shirt_size',
            field=models.CharField(choices=[('Для малышей', '0+ - 3+'), ('Для детей', '6+ - 12+'), ('Для подростков', '14+ - 17+'), ('Для взрослых', '18+')], default=0, max_length=2000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='agerestrictions',
            name='name',
            field=models.CharField(max_length=60),
        ),
    ]
