# Generated by Django 2.2 on 2019-04-08 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0012_remove_book_age_restrictions'),
        ('catalog', '0010_auto_20190408_2103'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AgeRestrictions',
        ),
    ]
