# Generated by Django 2.2 on 2019-04-23 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_genre_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='description',
        ),
    ]
